/* מאגר המכשירים. להוספת מכשיר חדש – פשוט הוסף אובייקט לרשימה. */
window.DEVICES = [
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    platform: 'ios',
    width: 393, height: 852,
    bezel: 12, radius: 55,
    notch: 'island',            // 'island' | 'notch' | 'hole' | 'none'
    safe: { top: 59, bottom: 34 },
    homeIndicator: true,
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    platform: 'ios',
    width: 430, height: 932,
    bezel: 12, radius: 58,
    notch: 'island',
    safe: { top: 59, bottom: 34 },
    homeIndicator: true,
  },
  {
    id: 'iphone-13-mini',
    name: 'iPhone 13 mini',
    platform: 'ios',
    width: 375, height: 812,
    bezel: 11, radius: 48,
    notch: 'notch',
    safe: { top: 50, bottom: 34 },
    homeIndicator: true,
  },
  {
    id: 'iphone-se',
    name: 'iPhone SE (2022)',
    platform: 'ios',
    width: 375, height: 667,
    bezel: 14, radius: 18,
    notch: 'none',
    safe: { top: 20, bottom: 0 },
    homeIndicator: false,
    chin: 62,                   // כפתור בית פיזי
  },
  {
    id: 'pixel-8',
    name: 'Pixel 8',
    platform: 'android',
    width: 412, height: 915,
    bezel: 11, radius: 38,
    notch: 'hole',
    safe: { top: 32, bottom: 24 },
    homeIndicator: true,
  },
  {
    id: 'galaxy-s24',
    name: 'Galaxy S24',
    platform: 'android',
    width: 360, height: 780,
    bezel: 10, radius: 34,
    notch: 'hole',
    safe: { top: 32, bottom: 24 },
    homeIndicator: true,
  },
  {
    id: 'galaxy-a54',
    name: 'Galaxy A54',
    platform: 'android',
    width: 385, height: 854,
    bezel: 12, radius: 30,
    notch: 'hole',
    safe: { top: 32, bottom: 24 },
    homeIndicator: true,
  },
  {
    id: 'ipad-mini',
    name: 'iPad mini',
    platform: 'ios',
    width: 744, height: 1133,
    bezel: 20, radius: 34,
    notch: 'none',
    safe: { top: 24, bottom: 20 },
    homeIndicator: true,
  },
];
